<?php
/**
 * Created by PhpStorm.
 * User: tsingsun
 * Date: 2018/8/15
 * Time: 下午10:00
 */

namespace app\controllers;


use yii\web\Controller;

class WsController extends Controller
{
    public $enableCsrfValidation = false;

    public function init()
    {
        \Yii::$app->user->enableSession = false;
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function behaviors()
    {
        $behaviors = parent::behaviors();
//        $behaviors['authenticator'] =[
//            'class'=>QueryParamAuth::className(),
//        ];
        return $behaviors;
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionOpen()
    {
        return 'hello';
    }

    public function actionMessage()
    {
        return rand(100,1000);
    }

    public function actionClose()
    {
        return 'close';
        /** @var Application */

    }
}